### ISSUE TITLE
Review invitation emails

### ISSUE THREAD

**Issue by ascuccimarra** [tarmac/pregnancy-control#172]
Check every flow, the email should state the username.

**Comment by ascuccimarra** [comment]
When it's through the individual buttons it doesn't send the username
![image](https://cloud.githubusercontent.com/assets/5980366/12679319/4dd5924c-c682-11e5-9762-288e284ea1a1.png)

**Comment by SabrinaTarmac** [comment]
Solved. 
E-mail includes "The username is" + username.
