### ISSUE TITLE
Document how to access catalyze server/db

### ISSUE THREAD

**Issue by machador** [tarmac/pregnancy-control#196]
We need the steps to access DB, and server on catalyze. The documentation should assume the user has an already created account and permissions to access the server, given by catalyze. 
It should include also explanations of basic management  commands to use the server.

**Comment by machador** [comment]
Alvaro documented basic access/management in doc: https://docs.google.com/document/d/18ZmU2LH6Y6PzUE-ayRpfScZtXdTJhdBdBevvj3udsCk/edit#heading=h.pq0uu...

**Comment by machador** [comment]
@elbosio once you get an account, please try to follow documented steps in alvaro's document to test if everything works ok.

**Comment by elbosio** [comment]
@machador @ascuccimarra I have DB and log access
