### ISSUE TITLE
Response on post contact and post message is not JSON also /devices explodes when there's no device

### ISSUE THREAD

**Issue by ascuccimarra** [tarmac/pregnancy-control#209]
It happens on those 2 endpoints 4sure but we should check the rest of the endpoints as well.
Example for posting contact request:
Previously the response was:

{"id":176,"created":"2016-02-04T17:15:40Z","read":false,"trash":false,"sentByMail":false,"title":"You have a contact request from Jane Doe","content":"Hi,\n
<br>
<br>\nJane Doe requested to add you as a contact.\nIf you know this person and you would like add him/her, please click 
<a href=\"https://pod02152.catalyzeapps.com/contact/acceptRequest?requesterId=2&amp;notificationId=176\" style=\"color: #2980b9;\">Accept<\u002fa>, or click 
    <a href=\"https://pod02152.catalyzeapps.com/contact/rejectRequest?requesterId=2&amp;notificationId=176\" style=\"color: #2980b9;\">Reject<\u002fa> otherwise.\n
        <br>
        <br>\nBest,\n
        <br>
        <br>\nSimpleCare Team","from":"jane","to":"alvaro@tarmac.io"}

Now it is:

Notification{created=Thu Feb 04 17:08:31 UTC 2016, type=CONTACT_REQUEST, read=false, sentByEmail=false, from=io.tarmac.pregnancyControl.Patient : 2, to=io.tarmac.pregnancyControl.HealthcareProvider : 17, title='You have a contact request from Jane Doe', content=Hi,
<br><br>
Jane Doe requested to add you as a contact.
If you know this person and you would like add him/her, please click <a href="http://simplecare-tarmactest.rhcloud.com/contact/acceptRequest?requesterId=2&amp;notificationId=187" style="color: #2980b9;">Accept</a>, or click <a href="http://simplecare-tarmactest.rhcloud.com/contact/rejectRequest?requesterId=2&amp;notificationId=187" style="color: #2980b9;">Reject</a> otherwise.
<br><br>
Best,
<br><br>
SimpleCare Team, deleted=false}

**Comment by SabrinaTarmac** [comment]
Send message, add contact and devices view working properly.
